[package]
name = "blockchain-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rocksdb = "0.22.0"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.8"
thiserror = { workspace = true }
tracing = { workspace = true }
