[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono = "0.4.39"
crossterm = "0.28.1"
ratatui = "0.29.0"
rig-core = "0.6.0"
rocksdb = "0.23.0"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
# tui-input = "0.11.1"
tui-textarea = "0.7.0"
uuid = "1.11.0"
