[package]
name = "ckb-example"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-sdk = "3.4.1"
ckb-std = "0.16.4"
anyhow = { workspace = true }
serde_json = { workspace = true }
ckb-types = "0.118.0"
hex = "0.4.3"
