[package]
name = "totp"
version = "0.1.0"
edition = "2021"

[dependencies]
totp-rs = "5.6.0"
anyhow = { workspace = true }
hmac = "0.12.1"
sha1 = "0.10.6"
base32 = "0.5.1"
time = "0.3.37"
byteorder = "1.5.0"
